# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes: []
  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true

# encoding explicit in comment
Encoding:
  Enabled: false

# Class and module documentation
Documentation:
  Enabled: false

DefWithoutParentheses:
  Enabled: false

FavorSprintf:
  Enabled: false
