alias amend=' git commit --amend'
alias be=' nocorrect bundle exec'
alias clone=' bundle exec rake db:test:clone_structure'
alias commit='git commit -a -m'
alias ctags='ctags -R --exclude=.git --exclude=log * ~/.rvm/gems/ruby-head/*'
alias debug_console='RAILS_ENV=prod_debug ./script/rails p'
alias debug_server='RAILS_ENV=prod_debug ./script/rails s -p 9091'
alias decrypt='gpg'
alias division='urxvt -name tango -fn "xft:courier" "#282800" -bd "#555500" -e ssh division'
alias encrypt='gpg -e'
alias gemdir='cd ~/.rvm/gems/ruby-1.9.2-p290'
alias gen='./script/generate'
alias gl=' git lg'
# This is to protect me from myself.
alias gpo='git push origin dev'
alias gpd='git push origin dev'
alias grc='git rebase --continue'
alias migrate='rake db:migrate && rake db:clone_all'
alias mysql=' mysql --default-character-set=utf8 --user=root --database=mysql -p'
alias openports='netstat -nape --inet'
alias pass='vim /home/blackman/Documents/passwds.txt'
alias prj='cd ~/prj/'
alias redo=' rake db:migrate:redo && rake db:test:clone_structure'
alias st=' git st && git lg'
alias tmux=" tmux -2"
alias u16="iconv -f utf16 -t utf8"
alias xephyr='Xephyr -ac -br -noreset -screen 1152x720 :1'
alias mountsan='udisks --mount /dev/disk/by-id/usb-SanDisk_Sansa_Clip_Zip_8_8609E9111222C2A80000000000000000-0:0'
alias umountsan='udisks --unmount /dev/disk/by-id/usb-SanDisk_Sansa_Clip_Zip_8_8609E9111222C2A80000000000000000-0:0'
alias todo='rake notes:custom ANNOTATION=TDB'
alias gdc='git diff --cached'
alias music='ncmpcpp'
alias right='setxkbmap -option ctrl:nocaps && xrandr --output HDMI1 --right-of LVDS1'
alias left='setxkbmap -option ctrl:nocaps && xrandr --output HDMI1 --left-of LVDS1'
alias smount='sudo mount -t cifs //fileserver/shared ~/mnt -o username=blackman,noexec'
alias red='cd ~blackman/prj/red'
alias servers='dig gigapan{1,2,3,4,5,8,9}.gigapan.com | grep gigapan | grep -v \; | sort -u'
alias stage='cd .. && popd && ey deploy -e $EY_ENV'
alias uat='cap uat deploy:migrations git:tag'
alias wemux='TERM=terminator /usr/local/bin/wemux'
alias prune='git remote prune origin'

# Fat finger protection program. Enlist Today!
alias cleara='clear'
alias clera='clear'
alias c='clear'
alias claer='clear'
alias cler='clear'

alias fixcaps='setxkbmap -option ctrl:nocaps'

