alias amend=' git commit --amend'
alias be=' nocorrect bundle exec'
alias clone=' bundle exec rake db:test:clone_structure'
alias commit='git commit -a -m'
alias ctags='ctags -R --exclude=.git --exclude=log * ~/.rvm/gems/ruby-head/*'
alias division='urxvt -name tango -fn "xft:courier" "#282800" -bd "#555500" -e ssh division'
alias gl=' git lg'
alias grc='git rebase --continue'
alias migrate='rake db:migrate && rake db:clone_all'
alias mysql=' mysql --default-character-set=utf8 --user=root --database=mysql -p'
alias openports='netstat -nape --inet'
alias prj='cd ~/prj/'
alias redo=' rake db:migrate:redo && rake db:test:clone_structure'
alias st=' git st && git lg'
alias tmux=" tmux -2"
alias xephyr='Xephyr -ac -br -noreset -screen 1152x720 :1'
alias mountsan='udisks --mount /dev/disk/by-id/usb-SanDisk_Sansa_Clip_Zip_8_8609E9111222C2A80000000000000000-0:0'
alias umountsan='udisks --unmount /dev/disk/by-id/usb-SanDisk_Sansa_Clip_Zip_8_8609E9111222C2A80000000000000000-0:0'
alias todo='rake notes:custom ANNOTATION=TDB'
alias gdc='git diff --cached'
alias music='ncmpcpp'
alias right='setxkbmap -option ctrl:nocaps && xrandr --output HDMI1 --right-of LVDS1'
alias left='setxkbmap -option ctrl:nocaps && xrandr --output HDMI1 --left-of LVDS1'
alias smount='sudo mount -t cifs //fileserver/shared ~/mnt -o username=blackman,noexec'
alias stage='cd .. && popd && ey deploy -e $EY_ENV'
alias wemux='TERM=terminator /usr/local/bin/wemux'
alias prune='git remote prune origin'

# Fat finger protection program. Enlist Today!
alias cleara='clear'
alias clera='clear'
alias c='clear'
alias claer='clear'
alias cler='clear'
alias xit='exit'

alias fixcaps='setxkbmap -option ctrl:nocaps'
